
title: Vijay Goswami
url: 'http://vijaygoswami.attrixtech.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Vijay Goswami  ## put your name
title: 'SOFTWARE &amp; WEB DEVELOPER'  ## your title
location: Agra, Uttar Pradesh, India


## Social Profiles
facebook: http://www.facebook.com/hexpit  ## your facebook account url
twitter: http://www.twitter.com/hexpit  ## your twitter account url
linkedin: http://www.linkedin.com/hexpit  ## your linkedin account url
dribbble: http://www.dribble.com/hexpit  ## you dribbble account url
foursquare: http://www.foursquare.com/hexpit  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
